"""empty message

Revision ID: 35d953ae3271
Revises: c6bd6522f09b
Create Date: 2021-09-13 15:36:23.841634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d953ae3271'
down_revision = 'c6bd6522f09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_permissions', sa.Column('delete', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles_permissions', 'delete')
    # ### end Alembic commands ###
