"""empty message

Revision ID: 42962623f718
Revises: e886ea766f73
Create Date: 2021-09-13 11:13:12.787950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42962623f718'
down_revision = 'e886ea766f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprises', sa.Column('delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entreprises', 'delete')
    # ### end Alembic commands ###
