"""empty message

Revision ID: c6bd6522f09b
Revises: 42962623f718
Create Date: 2021-09-13 11:27:20.654156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bd6522f09b'
down_revision = '42962623f718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_entreprises',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('delete', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'entreprise_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_entreprises')
    # ### end Alembic commands ###
