"""empty message

Revision ID: e886ea766f73
Revises: f5f553b8a87b
Create Date: 2021-08-31 14:16:42.538266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e886ea766f73'
down_revision = 'f5f553b8a87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('contenu', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'contenu')
    # ### end Alembic commands ###
