from marshmallow import Schema,fields


class UpdateEntrepriseSchema(Schema):
    id = fields.String()
    name = fields.String(required=False)
    raison_sociale = fields.String(required=False)
    forme_juridique = fields.String(required=False)
    commune = fields.String(required=False)
    wilaya = fields.String(required=False)
    nb_employes = fields.Integer(required=False)
    chiffre_affaires = fields.Float(required=False)
    capitale = fields.Float(required=False)
    quality = fields.String(required=False)
    secteur_activity = fields.String(required=False)
    contact = fields.String(required=False)
    fax = fields.String(required=False)
    address = fields.String(required=False)
    email = fields.String(required=False)
    logo = fields.String(required=False)
    facebook = fields.String(required=False)
    twitter = fields.String(required=False)
    linkedin = fields.String(required=False)
    website = fields.String(required=False)
    produits_service = fields.String(required=False)
    file = fields.String(required=False)
    Description = fields.String(required=False)
    year_creation = fields.DateTime(required=False)

class EntrepriseSchema(Schema):
    name = fields.String(required=True)
    commune = fields.String(required=False)
    wilaya = fields.String(required=False)

    quality = fields.String(required=False)

    fax = fields.String(required=False)
    address = fields.String(required=False)
    email = fields.String(required=False)
    logo = fields.String(required=False)
    facebook = fields.String(required=False)
    twitter = fields.String(required=False)
    linkedin = fields.String(required=False)
    website = fields.String(required=False)
    email_user = fields.String()
    file = fields.String(required=False)
    year_creation = fields.DateTime(required=False)

class getEntrepriseSchema(Schema):
    id = fields.String()
    name = fields.String(required=False)
    raison_sociale = fields.String(required=False)
    forme_juridique = fields.String(required=False)
    commune = fields.String(required=False)
    wilaya = fields.String(required=False)
    nb_employes = fields.Integer(required=False)
    chiffre_affaires = fields.Float(required=False)
    capitale = fields.Float(required=False)
    quality = fields.String(required=False)
    secteur_activity = fields.String(required=False)
    contact = fields.String(required=False)
    fax = fields.String(required=False)
    address = fields.String(required=False)
    email = fields.String(required=False)
    logo = fields.String(required=False)
    facebook = fields.String(required=False)
    twitter = fields.String(required=False)
    linkedin = fields.String(required=False)
    website = fields.String(required=False)
    produits_service = fields.String(required=False)
    file = fields.String(required=False)
    Description = fields.String(required=False)
    year_creation = fields.DateTime(required=False)
    user_avatar = fields.String(required=False)
    user_nom = fields.String(required=False)
    user_prenom = fields.String(required=False)
